---
extends: google
parserOptions:
  ecmaVersion: 6,
  sourceType: "module"
  ecmaFeatures:
    jsx: true
rules:
  semi: 2
  require-jsdoc:
  - error
  - require:
      FunctionDeclaration: false
      MethodDefinition: false
      ClassDeclaration: false
      ArrowFunctionExpression: false
  quotes:
  - off
  - double
  no-unused-vars:
  - off
  no-unused-vars:
  - error
  - vars: all
    args: after-used
    ignoreRestSiblings: false
plugins:
  - html
