# Generated by Django 2.1.5 on 2019-01-13 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(null=True)),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('editDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-publishDate', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=80, unique=True)),
                ('fridgedate', models.DateField(default=django.utils.timezone.now)),
                ('expires', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('fridgedate', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('comment', models.CharField(blank=True, max_length=80, null=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('sorting', models.IntegerField(help_text='A number.', verbose_name='Ordering')),
            ],
            options={
                'ordering': ('recipe_id', 'sorting', 'id'),
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='IngredientMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchaseAmount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('purchaseUnit', models.CharField(max_length=30, null=True)),
                ('store', models.CharField(max_length=30)),
                ('lastPurchaseDate', models.DateTimeField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Ingredient')),
            ],
            options={
                'ordering': ('ingredient__name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('editDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-publishDate', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('cook_method', models.IntegerField(choices=[(0, ''), (1, 'Grill'), (2, 'Oven'), (3, 'Slow Cooker'), (4, 'Stovetop')], default=0)),
                ('temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('directions', models.TextField(null=True)),
                ('source', models.CharField(blank=True, max_length=1000, null=True)),
                ('servings', models.IntegerField(default=0)),
                ('prep_time', models.IntegerField(default=0)),
                ('cook_time', models.IntegerField(default=0)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pinned', models.BooleanField(default=False)),
                ('banner_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('dish_type', models.IntegerField(choices=[(0, ''), (1, 'Dessert'), (2, 'Main'), (3, 'Pie'), (4, 'Salad'), (5, 'Side'), (6, 'Soup')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('shoppingListId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Ingredient')),
            ],
            options={
                'ordering': ('completed', 'name', 'shoppingListId'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='menu.Tag'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Recipe'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Recipe'),
        ),
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Recipe'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('recipe', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'recipe', 'amount', 'unit')},
        ),
    ]
